config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, :path_prefix => 'd'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  get 'home/about'
  match '/users', to: 'users#index', via: 'get'
  match '/users/:id', to: 'users#show', via: 'get'
  put 'admin/:id' => 'users#admin', :as => "admin"
  resources :projects
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { user: 0, admin: 1 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         


         has_many :projects

        def admin?
          @admin
        end

        def initialize(params = {})
          super (params)

        end

      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized  
protect_from_forgery with: :exception 

private


  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    #@project = Project.new
    @project = current_user.projects.build

  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    #@project = Project.new(project_params)
    @project = current_user.projects.build(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:id])
    redirect_to projects_path, notice: "Not Authorized To Edit Friend" if @project.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    after_action :verify_authorized
   
   
     def index
       authorize User
       
       @users = User.all
       
     end
   
     def show
       @user = User.find(params[:id])
       authorize @user
     end
   
     def admin
       user = User.find params[:id]
       user.update( :admin => true)
       redirect_to users_path
     end
   
     def authorized_user
       @k = current_user.admin?
       redirect_to users_path, alert: "NOT AUTHORIZED!! Only an admin can do this" if @k==false
     end

     def update
       @user = User.find(params[:id])
       authorize @user

       if @user.update_attributes(secure_params)
        redirect_to users_path, :success => "User updated"
      else
        redirect_to users_path, :alert => "Unable to update user"
      end
     end

     def destroy
      user = User.find(params[:id])
      authorize user
      user.destroy
      redirect_to users_path, :notice => "User deleted"
    end

    private

      def secure_params
        params.require(:user).permit(:role)
      end
   
   end
   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to "Home", root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item
          = link_to "About Us", home_about_path, class: "nav-link"
        %li.nav-item
          = link_to "Edit Profile", edit_user_registration_path, class: "nav-link"
        %li.nav-item
          = link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link"
      - else
        %li.nav-item
          = link_to "Sign Up", new_user_registration_path, class: "nav-link"
        %li.nav-item
          = link_to "Sign In", new_user_session_path, class: "nav-link"
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/home/about.html.haml
%h1 About Us
%p Learn more about our team and culture

app/views/home/index.html.haml
- if user_signed_in?
- else
  = link_to "Sign Up", new_user_registration_path, class: "btn btn-success"
  = link_to "Sign In", new_user_session_path, class: "btn btn-secondary"

%h1 Welcome to MyBaseCamp!
%p We hope you have productive fun
%P
  = image_tag "basecamp_img_logo.png", height: 250, class: "image"
%br

%P
  = link_to "All Projects", projects_path, class: "btn btn-success"
  = link_to "Members", users_path, class: "btn btn-success"
  = link_to "Add New Project", new_project_path, class: "btn btn-success"
%style
  h1 {
  text-align: center; 
  }
  p {
  text-align: center; 
  }
  

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>NewBasecamp</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

  </head>
  <body>
   <%= render "home/header"%>
   <div class= "container">
 <br/>
  <% if notice %>
    <%= render "layouts/alerts" %>
  <% end %>
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
     <br/>
    <%= f.input :description %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <%= @project.user_id%>
   
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User id:</strong>
    <%= project.user_id %>
  </p>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project, class: "btn btn-primary" %>
  <%= link_to "Back to projects", projects_path, class: "btn btn-dark" %>
  
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>
<div class="card-body">
  <div id="projects">
  <% @projects.each do |project| %>
    <% if project.user == current_user%>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project, class: "btn btn-primary" %>
    </p>
    <% end %>
  <% end %>
</div>    


</div>


<%= link_to "Add New Project", new_project_path, class: "btn btn-success" %>

app/views/projects/new.html.erb
<h1>New project</h1>


<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path, class: "btn btn-dark" %>
</div>

app/views/projects/show.html.erb
<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-primary" %> 
  <%= link_to "Back to projects", projects_path, class: "btn btn-dark" %> 
</div>
<br/>
<div>
  <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-danger" %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id(user) %>">
  <p>
    <strong>User ID</strong>
    <%= user.id %>
  </p>
  <p>
    <h4>email: <%= user.email %></h4>
  </p>
  <p>
    <h4>Role: <%= user.role.try(:titleize) %></h4>
  </p>
  <% if current_user.admin? && user == current_user %>
    <%= form_for user do |f| %>
      <%= f.select(:role, User.roles.keys.map { |role| [role.titleize, role] }) %>
      <%= f.submit "Update Role", class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <h1>Members</h1>

  <p>These are all the current members on the platform</p>
  
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user, class: "btn btn-success" %>
    </p>
  <% end %>
  
  <style>
    h1 {
      text-align: center;
    }
  
    p {
      font-size: 20px;
      text-align: center;
    }
  
    h4 {
      text-align: center;
    }
  </style>
</body>
</html>

app/views/users/show.html.erb
<div class="jumbotron text-center">
  <h1>
    <%= render @user %>
  </h1>
  <p>
    <%= button_to "Make Admin", { action: "admin" }, method: :put, class: "btn btn-success" %>
    <br>
    <%= link_to "Remove this User", users_path, class: "btn btn-danger" %>
  </p>
</div>

<style>
  .jumbotron {
    text-align: center;
  }

  p {
    text-align: center;
  }
</style>